version: 1.

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Starting install
      - npm install
  build:
    commands:
      - echo Starting build on `date`
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: './'
