version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Starting install
      - npm install
  build:
    commands:
      - echo Starting build on `date`
      - npm ci && npm run build && npm run start:prod
artifacts:
  files:
    - '**/*'
  base-directory: './'
